title = 'Linux Collective'
baseURL = 'https://linuxcollective.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'
enableInlineShortcodes = true
googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false
