name = "Linux Collective"
description = " Linux Collective by CloudNativeFolks"
homepage = "https://linuxcollective.github.io"
tags = ["docs", "minimal", "responsive", "light", "dark", "multilingual"]
features = []
min_version = "0.41.0"

[author]
  name = "Sangam Biradar"
  homepage = "https://github.com/sangam14"
